README.md
Hey, author of "Level up your Web Apps with Go" here (that's a mouthful). The O'Reilly page doesn't seem to have as much information as the Publisher's site (SitePoint).
=> Updated book with full blurb and better link

README.md
=> Tutorials  - spelling

README.md
The title Go: Up and Running has been cancelled by the author/publisher.
=> Remove "Go: Up and Running"

README.md
thanks to @PierreVannier for reporting it
closes #15
=> pdf moved for An Introduction To Programming In Go

README.md
List @calebdoxsey's book from O'Reilly and revise the description of his free book to match Amazon.
I can no longer find a Kindle version at http://www.amazon.com/Caleb-Doxsey/e/B00ITYLY9A/
=> Introduction to Programming in Go

README.md
Was in the text but not in the headline :wink:
=> Set Free flag for "Building Web Applications with Golang"

README.md
The cover wasn't loading because http://goinactionbook.com is currently down.
@goinggo @bketelsen @erikstmartin
=> revise Go in Action link/image

README.md
A Go Book "Go Programming by Example " by  Agus Kurniawan.
=> Addition of go programming by example

.travis.yml, README.md
thanks @dgryski. closes #34. closes #33
=> new book and updates

README.md
"Webapps in Go the anti textbook" had its 'f' lowercase
=> Added an uppercase F

README.md
Attempts to view prior image source results in HTTP 403 status code. I used the main image from the book page.
=> Get Programming with Go: Update image src

README.md
Im halfway through the book and thought that I would add it to the awesome list of GoBooks 👍
This is a great resource for writing microservices in Go and get a understadning of how to use docker with Go as well.
=> Added Building Microservices with Go book

README.md
Added [Build a SaaS app in Go](https://buildsaasappingo.com) to the Web development section.
=> added Build a SaaS app in Go

README.md
Add Programming with Google Go course to the list
=> Add Coursera Specialization : Programming with Google Go

README.md
Originally added in e14f66d1b07a3a854b457e496577f96933401473 #48
Looks like it’s no longer happening.
=> Remove Go Reactive Programming

README.md
Add go course in Udemy platform in resources section
=> Add go course in udemy platform

README.md
Course: Web Development with Google’s Go Programming Language
=> Add Course for Go Programming Language

README.md
The link for _Web Development With Go_ was updated to the latest link.
=> Update Web Development With Go with the latest link

README.md
=> Add hands-on engineering with golang

README.md
=> add Creative DIY Microcontroller Projects with Tinygo and WebAssembly

README.md
Please add `Mastering Go, 2nd edition`.
Thanks!
=> Add Mastering Go, 2nd edition

README.md
Hello @dariubs !
Thanks for maintaining this repository!
I wrote a book about the language : Practical Go Lessons, you can read it [here](https://www.practical-go-lessons.com/) !
I'm creating this PR to add my book to your repo.
Do not hesitate to contact me if something is not correct in my PR.
Have a nice day !
=> Add Practical Go Lessons

README.md
First, thanks for maintaining this repo. i think it is a fantastic idea.
I added my book: **Build Systems with Go: Everything a Gopher must Know**. The book is available at [Amazon](https://www.amazon.com/dp/B091FX4CZX) and the source code is available at is [GitHub repo](https://github.com/juanmanuel-tirado/savetheworldwithgo). The book explains the basic of the language and explores how to build systems using existing tools and libraries from the Go ecosystem. I added it in the Advanced Books section.
Thanks,
=> Added Build Systems with Go

README.md
The format of the cover was changed from .png to .jpg.
=> Fixed cover url for Go With The Domain e-book

README.md
PR to add Let's Go Further book to web development
=> Add Let's Go Further

README.md
The Pro Go book by Adam Freeman was added.
=> Add "Pro Go"

README.md
Adding free Beginner book on Go
=> Update README.md - new Go book

README.md
Adds "Go for DevOps" at the end of the section as instructed in the contributor.md.
=> add Go for DevOps

README.md
Add "Practical Go: Building Scalable Network and Non-Network Applications" to the list (I am the author).
Thank you for your contributions.
=> Add "Practical Go: Building Scalable Network and Non-Network Applications" 

README.md
Thank you for hosting this list and previously including my previous book (Hands-On Dependency Injection)
=> Add Beyond Effective Go - Part 1

README.md
Hello, please consider this book for the GoBooks directory. Thank you.
=> Adding entry for Go Faster

README.md
Hi,
Stjepan from Manning here. I thought this title might be a good match for your list. Thank you for considering it.
Best,
=> Added Learn Go with Pocket-Sized Projects

README.md
Fixed the covers of the 4 books published by Bitfield Consulting.
=> Fixed 4 images

README.md
Added newest version of "Mastering Go" which got recently released.
=> Added "Mastering Go, 4th edition"

README.md
Added the Go Programming - From Beginner to Professional: Learn everything you need to build modern software using Go, Second Edition Book to the list of beginner books
=> Added "Go Programming - From Beginner to Professional, 2nd Edition"

README.md
A foundational and practical guide for effectively learning the fundamental blockchain concepts and progressively building a blockchain from scratch in Go with gRPC. An interesting and challenging adventure that takes you from the foundational concepts and purpose through the technical design and implementation to the practical testing and usage of the proposed blockchain
=> Practical guide for building a blockchain from scratch in Go with gRPC

README.md
This PR addresses the issue raised regarding the missing book, The Go Programming Language by Alan A. A. Donovan and Brian W. Kernighan, in the GoBooks repository. The book is widely regarded as the definitive guide to Go programming, offering a comprehensive exploration of the language’s features.
-  Added The Go Programming Language to the GoBooks repository list.
- Included relevant details such as the authors, a description of the book, and the official website link.
This book is an authoritative resource and one of the most recommended in the Go community. It covers key Go concepts such as concurrency, error handling, and best practices, making it a valuable addition to any Go developer's learning path.
Issue Linked : #157 
Please review the changes and let me know if any …
=> PR for Adding 'The Go Programming Language' Book to GoBooks Repo
